# Generated by Django 4.2.7 on 2023-11-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnuserstatistics',
            name='pages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vpnuserstatistics',
            name='size_data_downloaded',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vpnuserstatistics',
            name='size_data_sent',
            field=models.FloatField(default=0),
        ),
    ]
