# Generated by Django 4.2.7 on 2023-11-10 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_site', '0002_alter_vpnuserstatistics_pages_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
